services:
  - type: web
    name: poweroil-masterchef-form
    env: node
    plan: free
    buildCommand: ""
    startCommand: "node server.js"
    envVars:
      - key: CLUBKONNECT_USER_ID
        value: CK101284801
      - key: CLUBKONNECT_API_KEY
        value: 5G2TFK1JZGX63T1J53U2TXY3732UT86155EK6R6ZI8LV8T72J63FCINN270U58K1
